### ISSUE TITLE
Modify flow without re-rendering

### ISSUE THREAD

**Issue by hspeace** [dkapur17/streamlit-flow#10]
This project is just what I need in terms of process creation! Currently, I re-render the flow by deleting the key of the flow. I would like to ask how to modify the flow information through code without re-rendering, such as creating nodes/modifying node names.

**Comment by dkapur17** [comment]
Hey @hspeace. Unfortunately, because of the way Streamlit works, assigning a key to the component ensures that component is not remounted when its arguments change. The problem is that state management is impossible without a key, so each flow component needs to have a key. As such the a work around is to delete the key and cause the component to re-render, as done in the Hackable State demo. 

It is possible that there is a cleaner work around than this, but I haven't been able to find one yet.

**Comment by hspeace** [comment]
@dkapur17  I see. I'm struggling with this too. I would like to know if you have implemented the relevant context-aware menu yourself, and whether can also implement drag and drop generation so that users can better create nodes through drag and drop. Please refer to https://reactflow.dev/examples/interaction/drag-and-drop. grateful!

**Comment by dkapur17** [comment]
Yes, the context menus in this library have been made specifically for this library and are not offered by Reactflow. I'll look into implementing drag-and-drop in the next version. Thanks for the feedback.

**Comment by LiShaoyu5** [comment]
> Hey @hspeace. Unfortunately, because of the way Streamlit works, assigning a key to the component ensures that component is not remounted when its arguments change. The problem is that state management is impossible without a key, so each flow component needs to have a key. As such the a work around is to delete the key and cause the component to re-render, as done in the Hackable State demo.
> 
> It is possible that there is a cleaner work around than this, but I haven't been able to find one yet.

I am trying to implement a demo with interactive process like [this](https://www.secretflow.org.cn/en/experience-zone/psi) and it seems that it can't be done by simply changing the styling CSS of nodes and edges. Is it possible to make streamlit_flow a widget that can be use in st.empty() and just switch to a new streamlit_flow every time?

**Comment by dkapur17** [comment]
@hspeace, this should be enabled in v1.5.0 through the new state management system. Check out https://stflow.streamlit.app/State_Modification_from_Python

**Comment by hspeace** [comment]
> @hspeace, this should be enabled in v1.5.0 through the new state management system. Check out https://stflow.streamlit.app/State_Modification_from_Python and let me know if this is what you're looking for,

So cool! st.session_state.curr_state is exactly what I need and makes other operations possible. grateful!
