### ISSUE TITLE
Node auto-width setting

### ISSUE THREAD

**Issue by yyahav** [dkapur17/streamlit-flow#11]
First thank you so much for this project! Awesome work!

Continuing #6 it's now possible to use only `width` parameter without having to use `style` with css width setting.

I tried to set the width to `auto`, without specifying the `width` parameter for the node, as css supports auto width:
`StreamlitFlowNode("1", (0, 0), {'content': "# Trace"}, 'input', 'right', style={'color': 'white', 'backgroundColor': '#00c04b', 'width': 'auto'})`

However it doesn't work, probably because width parameter should be specified for the render engine, as you mentioned on #6 

Is there any workaround to set auto width to a node?

Also, although using docstring """ to input the content, new lines are not rendered, and the only way to render it is by adding `<br>` at EOL.
```
StreamlitFlowNode("5", (0, 0), {
        'content': """### Variables
<details>
<summary>Click to view</summary>
isCustomer = true
age = 40.0
isReady = false
status = PENDING
</details>"""
```
<img width="220" alt="image" src="https://github.com/dkapur17/streamlit-flow/assets/88027106/b34bfc39-bdaf-48a9-afb5-2c3c47be2b2a">

```
StreamlitFlowNode("5", (0, 0), {
        'content': """### Variables
<details>
<summary>Click to view</summary>
isCustomer = true<br>
age = 40.0<br>
isReady = false<br>
status = PENDING<br>
</details>"""
```
<img width="206" alt="image" src="https://github.com/dkapur17/streamlit-flow/assets/88027106/038fd8fd-cbd8-49e8-8e97-59161e52f00c">

Is that just a limitation of rendering HTML?

Your work is much appreciated!

**Comment by dkapur17** [comment]
Hey @yyahav! I'll have to look at seeing if there is a way to auto compute the width of the node. There isn't any for now. As for the newline issue, that is the implementation of this markdown engine that single new lines are ignored - they might just be for better view of the editable text. If you want a line break, then you need to have two consecutive empty lines to show that.

**Comment by yyahav** [comment]
@dkapur17 yeah I figured it's the HTML render limitation... I solved it with `<br>`

Thank you for checking to see if there's a way to auto-width a node... would be a useful addition.

**Comment by yyahav** [comment]
@dkapur17 The PR adds auto-width support - if `width` is omitted in the StreamlitFlowNode definition the node will be set to auto-width.
Thanks!
