### ISSUE TITLE
no callback when modifying the node name

### ISSUE THREAD

**Issue by hspeace** [dkapur17/streamlit-flow#12]
hi I have a small question.
Using the context window to modify node data (content, source position, etc.) will not call back st.session_state[st.session_state.flow_key] .I need to click the flow again to synchronize it correctly. 
Can transfer the changes correctly like when creating the node?
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/47c84c62-47db-451b-9ab0-334d27a04cd9">

**Comment by dkapur17** [comment]
Hey @hspeace. Yes, state management between streamlit and react was a bit of a mess in the current version. Working on a new state management system. This issue should be fixed in the new release.
