### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by amosyou** [dkapur17/streamlit-flow#13]
Hi! Thanks for creating this library, it's been awesome to use. Is there any chance you could add a license for this package? It would make this package more accessible for people to use and develop with.

**Comment by dkapur17** [comment]
Hey @amosyou! I kind of just threw together this library for a task I needed to do for work. Wasn't really expecting it to catch the interest of too many others, and so I didn't have a license to begin with 😅. But thanks for this suggestion. I'll be adding an MIT License to the project.

**Comment by amosyou** [comment]
perfect! appreciate the quick response :))
