### ISSUE TITLE
Customize edge width

### ISSUE THREAD

**Issue by orby-fabian** [dkapur17/streamlit-flow#15]
How should I modify the `style` dict to customize the edge width?

I tried `border`, `border-width`, `font-weight` none of them have any effect.

Thanks

**Comment by dkapur17** [comment]
Hey @orby-fabian! Try using the `strokeWidth` property. For example `style={'strokeWidth': 10}`

**Comment by orby-fabian** [comment]
That worked! Thanks a lot!
