### ISSUE TITLE
Bug: markerStart and markerEnd are not picked up

### ISSUE THREAD

**Issue by JonnyDaenen** [dkapur17/streamlit-flow#20]
Currently, there seems to be no way to add a marker symbol to edges. This is supported by React Flow, as can be seen [here](https://reactflow.dev/examples/edges/markers).

**Tests conducted:**
```
StreamlitFlowEdge(
                "4-5",
                "4",
                "5",
                animated=False,
                label="testlabel",
                marker_end={
                    "type": "MarkerType.Arrow",
                    "stroke": "#FFFF72",
                },
                markerEnd={
                    "type": "MarkerType.Arrow",
                    "stroke": "#FFFF72",
                },
)
```

**Expected behavior:**
The kwargs parameter should be passed correctly, which does not seem to be the case currently. 

**Observed behavior:**
The markers do not appear in the UI

**Explanation:**
Potentially this is not accepted as a string?

**Alternative Option:**
Either marker_end (python style) or markerEnd could be added to support the marker symbols explicitly.

**Comment by dkapur17** [comment]
Hi @JonnyDaenen. Will include this in the next version!

**Comment by mmraavi** [comment]
anyway to make to make it fixed?
