### ISSUE TITLE
streamlit_flow has height parameter but no width?

### ISSUE THREAD

**Issue by NicolasMICAUX** [dkapur17/streamlit-flow#21]
Hi,
First, let me tell you how awesome your lib is!

2nd) I used `height=800` in `streamlit_flow(...)` to customize the component height.
Why isn't there a similar width argument?

I tried `style={"width": 800}` but it doesn't work.

Nicolas

**Comment by dkapur17** [comment]
Hey @NicolasMICAUX. Streamlit custom components don't have their own width attribute. It is set by streamlit automatically to fit the width of the page content.

**Comment by NicolasMICAUX** [comment]
Ok thanks for your answer, I wasn't aware!

**Comment by banoth223706** [comment]
Hi @NicolasMICAUX  @dkapur17 
In this "2nd) I used height=800 in streamlit_flow(...) to customize the component height." 
How can we give the height in "vh" instead of pixel's. As giving it in style is not working.
