### ISSUE TITLE
Directed edges

### ISSUE THREAD

**Issue by NicolasMICAUX** [dkapur17/streamlit-flow#22]
Hi,
It seems to me that `StreamlitFlowEdge` has no directed edge options. ( a bit like below)
![download](https://github.com/user-attachments/assets/0d42f524-32b3-4b1a-b934-570074d2402d)

I've seen that the class has `**kwargs` (**kwargs can be any other attribute on a React Flow node that you wish to manually set (not recommended))
I tried:
`markerEnd="arrow"` as found in https://reactflow.dev/api-reference/types/edge

No success.

Can you help me implement this (hopefully) small feature?

**Comment by dkapur17** [comment]
Hi @NicolasMICAUX. Will include this in the next version!

**Comment by NicolasMICAUX** [comment]
Nice! Thank you so much 🙏🏻
