### ISSUE TITLE
Image Support?

### ISSUE THREAD

**Issue by shuZro** [dkapur17/streamlit-flow#8]
Is there support for images in the nodes?

**Comment by dkapur17** [comment]
The `StreamlitFlowNode` class is a thin wrapper over the ReactFlow node, which doesn't directly support images. Adding support for images within nodes would require creating a custom ReactFlow node and a new `StreamlitFlowImageNode` class to interface with it. Will add this to the roadmap.

TL;DR: Currently, images in nodes are not supported.

**Comment by shuZro** [comment]
I was able to implement an image in the node using a background image in the styles.

**Comment by dkapur17** [comment]
This is a clever work around! Thanks for sharing.

**Comment by dkapur17** [comment]
Support for Images within nodes is supported natively through Markdown since v1.2.8! Check out the demo at https://stflow.streamlit.app/Markdown_Node.
