### ISSUE TITLE
Node Color and Shape Configuration

### ISSUE THREAD

**Issue by nityansuman** [dkapur17/streamlit-flow#9]
Hey @dkapur17  is it possible to make node of different colors? Either for all or make input, default and output nodes has a certain color or chape?

**Comment by dkapur17** [comment]
Hey @nityansuman. You can change the colors of the nodes by setting the `style` attribute. You can find an example at https://stflow.streamlit.app/Custom_Styles. There is no way to globally set colors - you need to individually set the style attribute on each node that you want to affect.
